matrix:
  include:
    - language: node_js
      node_js: 8
      env: TO_TEST=SERVEUR
        FOLDER=serveur
        NODE_ENV=development
    - language: objective-c
      os: osx
      osx_image: xcode9.2
      env: TO_TEST=CLIENT_LEGER
        FOLDER=client-leger
  fast_finish: true

before_install:
  - git diff --name-only HEAD~ | grep $FOLDER || {
      echo "No modifications within Job folder, stopping job process.";
      TO_TEST=;
    }
  - if [ "$TO_TEST" = "SERVEUR" ]; then cd serveur; fi
  - if [ "$TO_TEST" = "CLIENT_LEGER" ]; then cd client-leger/PolyPaintPro; pod repo update; fi
  - if [ "$TO_TEST" = "CLIENT_LOURD" ]; then cd client-lourd; fi

script:
  - if [ "$TO_TEST" = "SERVEUR" ]; then npm run build; fi
  - if [ "$TO_TEST" = "SERVEUR" ]; then npm run test; fi
  - if [ "$TO_TEST" = "CLIENT_LEGER" ]; then swiftlint; fi
  - if [ "$TO_TEST" = "CLIENT_LEGER" ]; then xcodebuild clean test -workspace PolyPaintPro.xcworkspace -scheme PolyPaintPro -destination "platform=iOS Simulator,OS=11.2,name=iPad Air 2" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet; fi
  - if [ "$TO_TEST" = "CLIENT_LOURD" ]; then xbuild PolyPaint.sln; fi

notifications:
  email: false
  slack: 
    rooms:
      - polypaintpro:2k3JgBABp3cePFJyKkDIp42Q#ci
    on_success: change # default: always
    on_failure: always # default: always

branches:
  only: 
    - master
