# Source : https://www.raywenderlich.com/143874/websockets-ios-starscream
# Correspond au fichier de dépendances aux librairies externes

# Uncomment this line to define a global platform for your project
# platform :ios, '11.0'
workspace 'PolyPaintPro'

target 'PolyPaintPro' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PolyPaintPro
  pod 'SwiftLint', '~> 0.24.2'
  pod 'Starscream', '~> 3.0.4'
  pod 'Alamofire', '~> 4.6.0'
  pod 'PromiseKit', '~> 4.5.1'

  target 'PolyPaintProTests' do
      inherit! :search_paths
      # Pods for testing
  end

  target 'PolyPaintProUITests' do
      inherit! :search_paths
      # Pods for testing
  end

end
