# Source : https://www.raywenderlich.com/143874/websockets-ios-starscream
# Correspond au fichier de dépendances aux librairies externes

# Uncomment this line to define a global platform for your project
# platform :ios, '11.0'

target 'PolyPaintPro' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PolyPaintPro
  pod 'Starscream', :git => 'https://github.com/daltoniam/Starscream', :branch => 'swift4'
end
